"""Ajout recrutement, candidat et entretien

Revision ID: 00d9b5c56a19
Revises: ce160890bf51
Create Date: 2025-06-20 23:54:55.568624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00d9b5c56a19'
down_revision = 'ce160890bf51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statut', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('offre_emploi_id', sa.Integer(), nullable=False))
        batch_op.alter_column('nom',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('candidat_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'offre_emploi', ['offre_emploi_id'], ['id'])
        batch_op.drop_column('etat')
        batch_op.drop_column('offre_id')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('jours_conges_restants')

    with op.batch_alter_table('entretien', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('offre_emploi_id', sa.Integer(), nullable=False))
        batch_op.alter_column('titre',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=150),
               nullable=False)
        batch_op.alter_column('participants',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('candidat_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('entretien_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'offre_emploi', ['offre_emploi_id'], ['id'])
        batch_op.drop_column('date_heure')
        batch_op.drop_column('offre_id')

    with op.batch_alter_table('offre_emploi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirements', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('statut', sa.String(length=50), nullable=True))
        batch_op.alter_column('titre',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('departement',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('prerequis')
        batch_op.drop_column('etat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offre_emploi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etat', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('prerequis', mysql.TEXT(), nullable=True))
        batch_op.alter_column('departement',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('titre',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('statut')
        batch_op.drop_column('requirements')

    with op.batch_alter_table('entretien', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offre_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_heure', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('entretien_ibfk_2'), 'offre_emploi', ['offre_id'], ['id'])
        batch_op.alter_column('candidat_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('participants',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('titre',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('offre_emploi_id')
        batch_op.drop_column('datetime')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jours_conges_restants', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    with op.batch_alter_table('candidat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offre_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('etat', mysql.VARCHAR(length=30), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('candidat_ibfk_1'), 'offre_emploi', ['offre_id'], ['id'])
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('nom',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('offre_emploi_id')
        batch_op.drop_column('statut')

    # ### end Alembic commands ###
