"""Schéma initial propre

Revision ID: 19c51bfa046f
Revises: 
Create Date: 2025-07-02 18:18:11.604320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19c51bfa046f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('motif', sa.String(length=100), nullable=False),
    sa.Column('justificatif', sa.String(length=200), nullable=True),
    sa.Column('etat', sa.String(length=50), nullable=True),
    sa.Column('impact_paie', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['employe_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('motif', sa.String(length=255), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['employe_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presence_journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('heure_arrivee', sa.Time(), nullable=True),
    sa.Column('heure_depart', sa.Time(), nullable=True),
    sa.Column('retard_minutes', sa.Integer(), nullable=True),
    sa.Column('heures_effectuees', sa.Float(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['employe_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('presence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retard_minutes', sa.Integer(), nullable=True))
        batch_op.drop_column('retard')
        batch_op.drop_column('statut')
        batch_op.drop_column('heures_travaillees')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heures_travaillees', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('statut', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('retard', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('retard_minutes')

    op.drop_table('presence_journal')
    op.drop_table('conge')
    op.drop_table('absence')
    # ### end Alembic commands ###
