"""Initial migration

Revision ID: 7f24b0771ca6
Revises: 00d9b5c56a19
Create Date: 2025-06-21 02:31:23.778246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f24b0771ca6'
down_revision = '00d9b5c56a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offre_emploi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_suppression', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offre_emploi', schema=None) as batch_op:
        batch_op.drop_column('date_suppression')

    # ### end Alembic commands ###
