"""Ajout telephone à candidat

Revision ID: c4f633acec0a
Revises: 7f24b0771ca6
Create Date: 2025-06-22 01:35:25.717895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f633acec0a'
down_revision = '7f24b0771ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telephone', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidat', schema=None) as batch_op:
        batch_op.drop_column('telephone')

    # ### end Alembic commands ###
