"""Initial migration

Revision ID: ce160890bf51
Revises: 
Create Date: 2025-06-20 22:33:00.123441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce160890bf51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('poste', sa.String(length=100), nullable=True),
    sa.Column('departement', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('type_contrat', sa.String(length=50), nullable=True),
    sa.Column('date_embauche', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('jours_conges_restants', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offre_emploi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=100), nullable=False),
    sa.Column('departement', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prerequis', sa.Text(), nullable=True),
    sa.Column('date_publication', sa.Date(), nullable=True),
    sa.Column('date_cloture', sa.Date(), nullable=True),
    sa.Column('etat', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    ) 
    op.create_table('absence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('type_absence', sa.String(length=100), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('motif', sa.Text(), nullable=True),
    sa.Column('justificatif', sa.Boolean(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('cv', sa.String(length=200), nullable=True),
    sa.Column('lettre_motivation', sa.String(length=200), nullable=True),
    sa.Column('date_soumission', sa.Date(), nullable=True),
    sa.Column('etat', sa.String(length=30), nullable=True),
    sa.Column('offre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['offre_id'], ['offre_emploi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('type_conge', sa.String(length=100), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('motif', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entretien',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidat_id', sa.Integer(), nullable=True),
    sa.Column('offre_id', sa.Integer(), nullable=True),
    sa.Column('titre', sa.String(length=100), nullable=True),
    sa.Column('date_heure', sa.DateTime(), nullable=True),
    sa.Column('duree', sa.Integer(), nullable=True),
    sa.Column('participants', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidat_id'], ['candidat.id'], ),
    sa.ForeignKeyConstraint(['offre_id'], ['offre_emploi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entretien')
    op.drop_table('conge')
    op.drop_table('candidat')
    op.drop_table('absence')
    op.drop_table('offre_emploi')
    op.drop_table('employee')
    # ### end Alembic commands ###
