"""Ajout colonne email à utilisateur

Revision ID: e6c4f3ad6542
Revises: 2e81e9874bde
Create Date: 2025-06-28 13:56:49.594593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6c4f3ad6542'
down_revision = '2e81e9874bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom_utilisateur', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('nom_complet', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('actif', sa.Boolean(), nullable=True))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('mot_de_passe_hash',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=128),
               nullable=True)
        batch_op.create_unique_constraint(None, ['nom_utilisateur'])
        batch_op.drop_column('nom')
        batch_op.drop_column('date_creation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_creation', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('nom', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('mot_de_passe_hash',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('actif')
        batch_op.drop_column('nom_complet')
        batch_op.drop_column('nom_utilisateur')

    # ### end Alembic commands ###
